services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./bot:/usr/src/app/bot
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./combined.log:/usr/src/app/combined.log
      - ./dados.db:/usr/src/app/dados.db
      - ./credenciais-google.json:/usr/src/app/credenciais-google.json
      - ./credentials.json:/usr/src/app/credentials.json
      - ./the_chosen_inscricoes.json:/usr/src/app/the_chosen_inscricoes.json
    networks:
      - bot-bridge

networks:
  bot-bridge:
    name: chatbot_shared_network
    external: true