services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./combined.log:/usr/src/app/combined.log
      - ./login.json:/usr/src/app/login.json
    networks:
      - bot-bridge

networks:
  bot-bridge:
    name: chatbot_shared_network
    external: true