sonar.projectKey=taynarad25_chatbot
sonar.organization=taynarad25

sonar.sources=bot,web,db.js,web.js
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
sonar.cpd.exclusions=test/**,**/*.test.js
