name: Deploy Chatbot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cloudflare Client
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Executar Deploy via SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          CF_COMMAND="cloudflared access tcp --hostname ssh.secretariacasaforte.com.br --service-token-id ${{ secrets.CF_CLIENT_ID }} --service-token-secret ${{ secrets.CF_CLIENT_SECRET }}"
          
          ssh -v -o StrictHostKeyChecking=no \
              -o ConnectTimeout=60 \
              -o ProxyCommand="$CF_COMMAND" \
              tayadm@ssh.secretariacasaforte.com.br \
              "cd /home/tayadm/github/chatbot && \
              git pull origin main && \
              docker network create chatbot_shared_network || true && \
              docker compose -f docker-compose.bot.yml up -d --build --force-recreate --no-deps whatsapp-bot"
